name: cypress-run

on: [push, pull_request]

jobs:
  cypress-run:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build and Start the Application
        run: |
          npm run build
          npm run start & # replace with `npm run dev` if you want to use the development server

      # Cypress action manages installing/caching npm dependencies and Cypress binary.
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          # build: npm run build
          # start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
          browser: chrome

        env:
          CYPRESS_TEST_EMAIL: ${{ secrets.CYPRESS_TEST_EMAIL }}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
